name: Deploy To EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH로 EC2에 접속하기
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}             # EC2의 주소
          username: ${{ secrets.EC2_USERNAME }}     # EC2 접속 username
          key: ${{ secrets.EC2_PRIVATE_KEY }}       # EC2 Key 파일의 내용
          script_stop: true                         # 명령어 실패 시 워크플로우 실패 처리
          script: |
            cd /home/ubuntu/kosta02
            git pull origin main
            mvn clean package
            sudo fuser -k -n tcp 8080 || true
            nohup java -jar target/*SNAPSHOT.jar > ./output.log 2>&1 &
